//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopErpApi.Models.DBModel
{
    /// <summary>
    /// Defines the <see cref="Product_Expend_Rate_Config" />.
    /// </summary>
    public partial class Product_Expend_Rate_Config
    {
        /// <summary>
        /// Gets or sets the id.
        /// </summary>
        public int id { get; set; }

        /// <summary>
        /// Gets or sets the product_id.
        /// </summary>
        public string product_id { get; set; }

        /// <summary>
        /// Gets or sets the product_name.
        /// </summary>
        public string product_name { get; set; }

        /// <summary>
        /// Gets or sets the product_category.
        /// </summary>
        public int product_category { get; set; }

        /// <summary>
        /// Gets or sets the product_type.
        /// </summary>
        public int product_type { get; set; }

        /// <summary>
        /// Gets or sets the high_expend_rate.
        /// </summary>
        public double high_expend_rate { get; set; }

        /// <summary>
        /// Gets or sets the low_expend_rate.
        /// </summary>
        public double low_expend_rate { get; set; }

        /// <summary>
        /// Gets or sets the create_time.
        /// </summary>
        public System.DateTime create_time { get; set; }

        /// <summary>
        /// Gets or sets the update_time.
        /// </summary>
        public System.DateTime update_time { get; set; }
    }
}
