//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopErpApi.Models.DBModel
{
    /// <summary>
    /// Defines the <see cref="Staff" />.
    /// </summary>
    public partial class Staff
    {
        /// <summary>
        /// Gets or sets the id.
        /// </summary>
        public int id { get; set; }

        /// <summary>
        /// Gets or sets the leader_id.
        /// </summary>
        public int leader_id { get; set; }

        /// <summary>
        /// Gets or sets the name.
        /// </summary>
        public string name { get; set; }

        /// <summary>
        /// Gets or sets the password.
        /// </summary>
        public string password { get; set; }

        /// <summary>
        /// Gets or sets the user_type.
        /// </summary>
        public string user_type { get; set; }

        /// <summary>
        /// Gets or sets the salary.
        /// </summary>
        public decimal salary { get; set; }

        /// <summary>
        /// Gets or sets the sell_product_type.
        /// </summary>
        public string sell_product_type { get; set; }

        /// <summary>
        /// Gets or sets the create_time.
        /// </summary>
        public System.DateTime create_time { get; set; }

        /// <summary>
        /// Gets or sets the update_time.
        /// </summary>
        public System.DateTime update_time { get; set; }
    }
}
