//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopErpApi.Models.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int id { get; set; }
        public int leader_id { get; set; }
        public string name { get; set; }
        public string password { get; set; }
        public string user_type { get; set; }
        public decimal salary { get; set; }
        public string sell_product_type { get; set; }
        public System.DateTime create_time { get; set; }
        public System.DateTime update_time { get; set; }
    }
}
